dependencies {
    if (project.hasProperty("smartMoving")) {
        devOnlyNonPublishable(rfg.deobf("net.smart:SmartMoving:1.7.10-15.8.2-maka"))
        devOnlyNonPublishable(rfg.deobf("api.player:PlayerAPI:1.7.10-1.4.1-maka"))
        devOnlyNonPublishable(rfg.deobf("net.smart:SmartRender:1.7.10-2.1"))
    }
}
